services:
  api:
    # Сделать images а не build
    build:
      context: .
      dockerfile: Dockerfile
      target: prod

    restart: unless-stopped

    env_file:
      - .env.prod

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
        
  db:
    restart: unless-stopped

    env_file:
      - .env.prod



volumes:
  postgres_data: