openapi: 3.0.3
info:
  title: Firebase Auth API
  version: 1.0.0
  description: 'My Django boilerplate for quick start >:'
paths:
  /api/auth/firebase/:
    post:
      operationId: auth_firebase_create
      description: Проверка id_token, создание пользователя в бд, выдача доступа
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FirebaseAuth'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirebaseAuth'
          description: ''
  /api/auth/token/refresh/:
    post:
      operationId: auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/users/me/:
    get:
      operationId: users_me_retrieve
      description: Получение личных данных пользователем
      tags:
      - users
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: users_me_update
      description: Получение личных данных пользователем
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: users_me_partial_update
      description: Получение личных данных пользователем
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/me/deletion/:
    post:
      operationId: users_me_deletion_create
      description: Добавление пользователя в очередь для удаления
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteUser'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUser'
          description: ''
  /api/users/me/deletion/cancel/:
    post:
      operationId: users_me_deletion_cancel_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelDeleteUser'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelDeleteUser'
          description: ''
components:
  schemas:
    CancelDeleteUser:
      type: object
      properties:
        id_token:
          type: string
      required:
      - id_token
    DeleteUser:
      type: object
      properties:
        id_token:
          type: string
        reason:
          type: string
      required:
      - id_token
      - reason
    FirebaseAuth:
      type: object
      properties:
        id_token:
          type: string
      required:
      - id_token
    PatchedUser:
      type: object
      properties:
        username:
          type: string
          maxLength: 30
        display_name:
          type: string
          maxLength: 25
        email:
          type: string
          format: email
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        username:
          type: string
          maxLength: 30
        display_name:
          type: string
          maxLength: 25
        email:
          type: string
          format: email
          readOnly: true
          nullable: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - email
      - updated_at
      - username
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
