# Generated by Django 6.1 on 2026-09-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_seen',
            new_name='last_activity',
        ),
    ]
