# Generated by Django 6.1 on 2026-09-13 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('delete_at', models.DateTimeField(db_index=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на удаление аккаунта',
                'verbose_name_plural': 'Запросы на удаление аккаунтов',
            },
        ),
    ]
