# Generated by Django 6.1 on 2026-09-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_accountdeletionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
    ]
